version: '3.7'

services:
  hashthink_postgres: 
    image: postgres
    container_name: hashthink_postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
    - POSTGRES_DB=hashthink_db_development
    - POSTGRES_USER=hashthink_service
    - POSTGRES_PASSWORD=123456    

  hashthink_adminer: 
    image: adminer
    container_name: hashthink_adminer
    ports:
      - 8080:8080
    links:
      - hashthink_postgres
    depends_on:
      - hashthink_postgres